### ISSUE TITLE
Update file connector document to version 2.0.22

### ISSUE THREAD

**Issue by dulanjalidilmi** [wso2-extensions/esb-connector-file#110]
**Description:**
With file connector 2.0.22, in **file create** operation parameter ``source`` has changed to ``filePath``.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by anupama-pathirage** [comment]
Moved to https://github.com/wso2/docs-mi/issues/789
