### ISSUE TITLE
[Improvement] Unable to use relative paths to access files

### ISSUE THREAD

**Issue by dulanjalidilmi** [wso2-extensions/esb-connector-file#114]
**Description:**
It's convenient for the user if files can be accessed by providing relative paths as well

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by anupama-pathirage** [comment]
Moved to https://github.com/wso2/micro-integrator/issues/3539
