### ISSUE TITLE
[Doc] [3.0.0] Update file connector copy operation 

### ISSUE THREAD

**Issue by dulanjalidilmi** [wso2-extensions/esb-connector-file#123]
**Description:**
With file connector 3.0.0 release, 2 new parameters are introduced for copy operation

If the user wants to use private key for SFTP connection following 2 parameters can be used.
sftpIdentities - Location of the private key
sftpIdentityPassphrase - Passphrase of the private key
Eg : 
``
<sftpIdentities>File path of the private key</sftpIdentities>
<sftpIdentityPassphrase>passphrase of the private key</sftpIdentityPassphrase>
``

**Related Issues:**
https://github.com/wso2/product-ei/issues/5174

**Comment by samgnaniah** [comment]
Fixed with https://github.com/wso2/docs-ei/pull/1743

**Comment by anupama-pathirage** [comment]
Closing as the above PR fixed the issue
