### ISSUE TITLE
WSO2 EI7 Error connector after redeploying CAR 

### ISSUE THREAD

**Issue by jcrodesp84** [wso2-extensions/esb-connector-file#140]
**Description:**
When second API call is made, connector fails at initialising phase. Exception is not visible.

**Affected Product Version:**

EI 7.1.x
MI 1.2.x

**Steps to reproduce:**

1.     Make a working scenario using File connector.
2.     Burn the logic into a CAR application, and create a simple createDirectory process.
3.     As per the code, init will be done at the first message only. For other messages it will not get called.
4.     Redeploy the same CApp.
5.     When doing the same invoke and create a new directory again, the console show the next errror

Caused by: java.lang.ClassCastException: org.wso2.carbon.connector.connection.FileSystemHandler cannot be cast to org.wso2.carbon.connector.connection.FileSystemHandler

[Issue.log](https://github.com/wso2-extensions/esb-connector-file/files/5622216/Issue.log)

**Comment by anupama-pathirage** [comment]
Moved to https://github.com/wso2/micro-integrator/issues/3537
