### ISSUE TITLE
Missing config in local file system connection

### ISSUE THREAD

**Issue by abeykoon** [wso2-extensions/esb-connector-file#141]
**Description:**

When a new `Local File Connection` is created, following config is not getting preserved in the local entry xml source. 

```
<fileLockScheme>Local</fileLockScheme>
```

**Comment by abeykoon** [comment]
The issue is with the integration studio. If we set the `File Locking Behaviour` when we create the new connection it is set. 
However, if we edit it and try to set it later, it does not get set or updated.

![image](https://user-images.githubusercontent.com/4967046/102379719-2970f600-3fed-11eb-9b16-dee0af75dc92.png)

**Comment by tharakamd** [comment]
Fixed with the PR https://github.com/wso2/integration-studio/pull/716
