### ISSUE TITLE
Update file connector sftpIdentities parameter and Passphrase parameter

### ISSUE THREAD

**Issue by karunarathneeshani** [wso2-extensions/esb-connector-file#147]
**Description:**
As per the current wso2 file connector implementation, it is only supported for one sftpIdentities parameter and sftpIdentityPassphrase to specify the location of the private key and Passphrase of the private key for either source or the destination. 
It is required to improve the file connector to specify the location of the private key and Passphrase for both the source server and the destination server.

**Related Issues:**
https://github.com/wso2-extensions/esb-connector-file/issues/123

**Comment by anupama-pathirage** [comment]
Moved to https://github.com/wso2/micro-integrator/issues/3536
