### ISSUE TITLE
Implementing the filePattern parameter for the move operation in latest File connector 4.0.4

### ISSUE THREAD

**Issue by karunarathneeshani** [wso2-extensions/esb-connector-file#157]
**Description:**
As the filePattern parameter is not available for the move operation in the latest File connector 4.0.4 implementation, it is required to implement this parameter for the file connector move operation as this parameter is available in previous file connector versions.

**Suggested Labels:**
FileConnector-4.0.4

**Comment by SanojPunchihewa** [comment]
Fixed with https://github.com/wso2-extensions/esb-connector-file/pull/158 and available in file-connector **v4.0.5** and above.
