### ISSUE TITLE
Retry feature for file connector mediator

### ISSUE THREAD

**Issue by vikumkbv** [wso2-extensions/esb-connector-file#168]
**Description:**
Requesting a retry feature for file connector mediator(inside integration studio) as what is available in Inbound Endpoint (retry on failure)

**Affected Product Version:** 6.6.0

**Steps to reproduce:** No retry feature for the file connector mediator

**Comment by anupama-pathirage** [comment]
Moved to https://github.com/wso2/micro-integrator/issues/3533
